---
# - name: Wait for ssh availability
#   hosts: aws_ec2
#   tasks:
#   - name: Ensure ssh port is open
#     wait_for:
#       port: 22
#       delay: 10
#       timeout: 100
#       search_regex: OpenSSH
#       host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
#     vars:
#       ansible_connection: local

- name: Install Docker on EC2
  hosts: tag_Name_dev_server
  become: yes
  become_user: root
  tasks:
  - name: Make sure docker and docker-compose are available
    yum:
      name:
      - python3-pip
      - docker
      update_cache: yes
      state: present
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      dest: /usr/local/bin/docker-compose
      mode: +x
  - name: Ensure docker daemon is running
    systemd:
      name: docker
      state: started
  - name: Install docker python module
    become: yes
    become_user: ec2-user
    pip:
      name:
      - docker
      - docker-compose

- name: Add ec2-user to docker group
  hosts: tag_Name_dev_server
  become: yes
  become_user: root
  tasks:
  - name: Add ec2-user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server session
    meta: reset_connection

- name: Start docker containers
  hosts: tag_Name_dev_server
  vars_files:
  - project-vars.json
  tasks:
  - name: Copy docker-compose file
    copy:
      src: /home/luisfguzman/bootcamp-java-mysql/docker-compose.yaml
      dest: /home/ec2-user/docker-compose.yaml
  - name: Docker login to Docker Hub
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1
      username: foundryvault
      password: "{{docker_password}}"
  - name: Start containers from compose file
    community.docker.docker_compose:
      project_src: /home/ec2-user
      #state: present # default state | docker-compose up
