- name: Copy docker-compose file
  copy:
    src: docker-compose.yaml
    dest: /home/docker-user/docker-compose.yaml
- name: Docker login to Docker Hub
  community.docker.docker_login:
    registry_url: {{docker_registry}} #https://index.docker.io/v1
    username: {{docker_username}} #foundryvault
    password: "{{docker_password}}"
- name: Start containers from compose file
  community.docker.docker_compose:
    project_src: /home/docker-user
    state: present # default state | sames asdocker-compose up